//
//  Log.swift
//  Keep
//
//  Created by Michael Amiro on 22/04/2025.
//

import Foundation
import Logging

/// Model representing a single log entry captured by Keep.
struct Log: Codable {
    public let id: String
    public let level: Logging.Logger.Level
    public let description: String
    public let timestamp: Date
    public let metadata: Logging.Logger.Metadata?
    public let source: String?
    public let file: String
    public let function: String
    public let line: UInt
    public var pinned: Bool

    @MainActor
    var tag: LogTag {
        LogTagger.tag(for: metadata, description: description)
    }

    /// Creates a log entry value.
    ///
    /// - Parameters:
    ///   - id: Unique identifier for the log entry. A new UUID is generated by default.
    ///   - level: Severity associated with the message.
    ///   - description: Human-readable body of the log.
    ///   - timestamp: Time the log was produced.
    ///   - metadata: Additional metadata attached to the entry.
    ///   - source: Subsystem that generated the message.
    ///   - file: File identifier captured at call site.
    ///   - function: Function where the log originated.
    ///   - line: Line number where the log originated.
    ///   - pinned: Indicates whether the entry should appear in the pinned section.
    init(
        id: String = UUID().uuidString,
        level: Logging.Logger.Level,
        description: String,
        timestamp: Date,
        metadata: Logging.Logger.Metadata? = nil,
        source: String? = nil,
        file: String = #fileID,
        function: String = #function,
        line: UInt = #line,
        pinned: Bool = false
    ) {
        self.id = id
        self.level = level
        self.description = description
        self.timestamp = timestamp
        self.metadata = metadata
        self.source = source
        self.file = file
        self.function = function
        self.line = line
        self.pinned = pinned
    }

    enum CodingKeys: String, CodingKey {
        case id
        case level
        case description
        case timestamp
        case metadata
        case source
        case file
        case function
        case line
        case pinned
    }

    init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(String.self, forKey: .id)
        self.level = try container.decode(Logging.Logger.Level.self, forKey: .level)
        self.description = try container.decode(String.self, forKey: .description)

        let timestamp = try container.decode(String.self, forKey: .timestamp)
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        self.timestamp = formatter.date(from: timestamp) ?? Date()

        self.metadata = try container.decodeIfPresent(Logging.Logger.Metadata.self, forKey: .metadata)
        self.source = try container.decodeIfPresent(String.self, forKey: .source)
        self.file = try container.decode(String.self, forKey: .file)
        self.function = try container.decode(String.self, forKey: .function)
        self.line = try container.decode(UInt.self, forKey: .line)
        self.pinned = try container.decodeIfPresent(Bool.self, forKey: .pinned) ?? false
    }

    func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.id, forKey: .id)
        try container.encode(self.level, forKey: .level)
        try container.encode(self.description, forKey: .description)
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        try container.encode(formatter.string(from: self.timestamp), forKey: .timestamp)
        try container.encodeIfPresent(self.metadata, forKey: .metadata)
        try container.encodeIfPresent(self.source, forKey: .source)
        try container.encode(self.file, forKey: .file)
        try container.encode(self.function, forKey: .function)
        try container.encode(self.line, forKey: .line)
        try container.encode(self.pinned, forKey: .pinned)
    }
}

extension Log {
    func matches(_ searchTerm: String) -> Bool {
        let term = searchTerm.lowercased()

        return id.lowercased().contains(term)
            || level.rawValue.lowercased().contains(term)
            || description.lowercased().contains(term)
            || source?.lowercased().contains(term) ?? false
            || file.lowercased().contains(term)
            || function.lowercased().contains(term)
            || "\(line)".contains(term)
            || timestamp.description.lowercased().contains(term)
            || metadata?.matches(term) ?? false
    }
}

extension Log {
    static var samples: [Log] {
        let anchor = Date()
        return [
            Log(
                level: .critical,
                description: "Service outage detected for payments",
                timestamp: anchor.addingTimeInterval(-15),
                metadata: [
                    "component": .string("Payments"),
                    "region": .string("us-east-1"),
                    "status": .string("down")
                ],
                source: "Monitoring",
                pinned: true
            ),
            Log(
                level: .error,
                description: "Failed to decode response payload",
                timestamp: anchor.addingTimeInterval(-30),
                metadata: ["endpoint": .string("/v1/items")],
                source: "Networking",
                pinned: true
            ),
            Log(
                level: .warning,
                description: "Retrying request after timeout",
                timestamp: anchor.addingTimeInterval(-45),
                metadata: [
                    "attempt": .stringConvertible(2),
                    "duration": .string("320ms")
                ],
                source: "Networking"
            ),
            Log(
                level: .info,
                description: "Fetched 12 items from /v1/items",
                timestamp: anchor.addingTimeInterval(-60),
                metadata: ["status": .string("200"), "duration": .string("120ms")],
                source: "Networking"
            ),
            Log(
                level: .debug,
                description: "Refreshing cached configuration",
                timestamp: anchor.addingTimeInterval(-75),
                metadata: ["feature": .string("RemoteConfig")],
                source: "KeepPreview"
            ),
            Log(
                level: .info,
                description: "UIViewController deinit",
                timestamp: anchor.addingTimeInterval(-90),
                metadata: ["feature": .string("RemoteConfig")],
                source: "KeepPreview"
            )
        ]
    }
}
